version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - wp_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./:/var/www/html/wp-content/plugins/multisite-taxonomies
  wpcli:
    depends_on:
      - db
      - wordpress
    image: tatemz/wp-cli
    volumes_from:
      - wordpress
    links:
      - db:mysql
    entrypoint: wp
volumes:
    wp_db:
