# CircleCI V2 config file
# See https://circleci.com/docs/2.0/configuration-reference/ for more details on syntax.
# $HSPH_WEBTEAM_GITHUB_TOKEN is a global organisation environment variable in the 'org-global' context (see https://circleci.com/docs/2.0/contexts/).
# We use a GitHub token for composer to avoid API limit rate errors (see https://getcomposer.org/doc/articles/troubleshooting.md#api-rate-limit-and-oauth-tokens).
version: 2
jobs:
  testing:
    docker:
      - image: circleci/php:apache-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: composer config -g github-oauth.github.com $HSPH_WEBTEAM_GITHUB_TOKEN
      - run: php -v
      - run: composer install
      - run: ./vendor/bin/phpcs ./
workflows:
  version: 2
  build-test:
    jobs:
      - testing:
          context: org-global
